<?php
/** @var Magento\Framework\View\Element\Template $block */
/** @var Orba\Blog\ViewModel\Post $postVm */
/** @var Magento\Framework\Escaper $escaper*/
$postVm = $block->getData('post_vm');
$cout=$postVm->getCount();
?>
<div class="blog-post-list">
    <h1><?= __('Blog posts') ?></h1>
    <ul>
        <?php foreach ($postVm->getList() as $post): ?>
            <li>
                <a href="<?= $block->getUrl('blog/post/detail', ['id' => $post->getData('id')]) ?>">
                    <?= $escaper->escapeHtml($post->getData('title')) ?>
                </a>
            </li>
        <?php endforeach ?>
    </ul>
    <p>
       <?= __('suma postów (count post): %1', $cout)?></p>

</div>
